### ISSUE TITLE
Source Array Error On Token Transfer Via Loop

### ISSUE THREAD

**Issue by Geordie-R** [Remmeauth/remme-client-dotnet#9]
'Source array was not long enough. Check srcIndex and length, and the array's lower bounds'

I get this error when putting token transfer code in a loop.

The error specifically happens on this line of my code

`  var transactionResult = await this.m_client.Token.Transfer(toAddress, totalQty);`

Please find below an example of how i created the error.  Please note: I may have broken some golden rules I'm new to c#. I have replaced my code with static variables.

`private async void Go()
        {
            uint HowManyLoops = Convert.ToUInt32(100);
            for (int i = 0; i < HowManyLoops; i++)
            {

                string toAddress = "036a8255d5d63affa48a821bdb1bcccd932b4fd29b78b0ca1246a14de8ad777a4f";        
                ulong totalQty = Convert.ToUInt64(1);

                var transactionResult = await this.m_client.Token.Transfer(toAddress, totalQty);

              //add to data grid as pending

                transactionResult.OnREMChainMessage += (sender, e) =>
                {

                    if (e.Status == BatchStatusEnum.COMMITTED)
                    {             
                        transactionResult.CloseWebSocket();

                        //amend grid row as commited

                    }
                   
                    else if (e.Status == BatchStatusEnum.NO_RESOURCE)
                    {
                       //no money etc

                    }
                };
                transactionResult.ConnectToWebSocket();
            }

        }`

Please find below exception message.

System.ArgumentException
  HResult=0x80070057
  Message=Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
  Source=mscorlib
  StackTrace:
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at REMME.Auth.Client.Crypto.EcKeyPair.Sign(Byte[] input)
   at REMME.Auth.Client.Implementation.RemmeAccount.Sign(Byte[] data)
   at REMME.Auth.Client.Implementation.RemmeTransactionService.<CreateTransaction>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at REMME.Auth.Client.Implementation.RemmeToken.<TransferByAddress>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at REMME.Auth.Client.Implementation.RemmeToken.<Transfer>d__8.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Remme_Testing.usrSendTransactions.<Go>d__9.MoveNext() in C:\Users\r\OneDrive\Documents\Visual Studio 2015\Projects\Remme Test\Remme Test C\Remme Testing\Remme Testing\usrSendTransactions.cs:line 94

**Comment by Geordie-R** [comment]
This problem happens when a byte array was input with 31 bytes in sig.R.ToByteArrayUnsigned() which caused the exception in ECKeyPair.cs

`/// <summary>
        /// Calculates ECDSA signature for  given input
        /// </summary>
        public byte[] Sign(byte[] input)
        {
            var signer = new DeterministicECDSA();
            var privKey = new ECPrivateKeyParameters(_privateKey, _ecParams);

            signer.SetPrivateKey(privKey);
            var sig = ECDSASignature.FromDER(signer.Sign(input)).ToCanonical();
           
            byte[] result = new byte[64];
            **Array.Copy(sig.R.ToByteArrayUnsigned(), 0, result, 0, 32);**
            Array.Copy(sig.S.ToByteArrayUnsigned(), 0, result, 32, 32);

            return result;
        }`

**Comment by apadenko** [comment]
Hello, @Geordie-R 

Thank you for your interest and activity!
You found a rarely reproducible bug, which we didn't discover in our testing process. 
This issue was very useful for us, so we may improve our integration library with the help of that. 

You were right. 
The problem occurred because _S_ and _R_ signature properties sometimes have a different length from 32 bytes.  

The fix now is in the repository code base and you may download [0.3.5](https://www.nuget.org/packages/REMME.Auth.Client/0.3.5) library version from NuGet
